# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="groovyfml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[26,)" #mandatory (24 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/TheSledgeHammer/GroovyForge/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="groovyforge" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="2.5.0" #mandatory
 # A display name for the mod
displayName="GroovyForge" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/TheSledgeHammer/GroovyForge" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="groovyforgelogo.png" #optional
# A text field displayed in the mod UI
credits="Apache Groovy" #optional
# A text field displayed in the mod UI
authors="TheSledgeHammer" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A Language Adapter for using Apache Groovy in Minecraft Modding
'''
